name: CI

on:
  push:
    branches: [main]

jobs:
  testsuite_php_8_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP 8.1 Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, mbstring, simplexml, pdo, pdo_mysql

      - name: Install Packages in the temporary container
        working-directory: ./
        run: composer install

      - name: Run tests with PHP 8.1
        working-directory: ./
        run: vendor/bin/phpunit tests
